# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Import additional configuration files
import :
- ~/.config/alacritty/colors/normal_dark.yaml
- ~/.config/alacritty/fonts/font.yaml

# TERM variable
TERM: alacritty

window:
  dimensions:
    columns: 0
    lines: 0

  position:
    x: 0
    y: 0

  opacity: 1.0

  padding:
    x: 0
    y: 0
  dynamic_padding: false

  decorations: none #values: full/none

  startup_mode: Windowed #values: Windowed/Maximized/Fullscreen

  #title: Alacritty

  dynamic_title: true

  decorations_theme_variant: dark #values: dark/light/None


selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style: Underline

live_config_reload: true
draw_bold_text_with_bright_colors: true
