font:
  normal:
    family: "Fira Code"
    
  bold:
     family: monospace

  italic:
     family: monospace

  bold_italic:
     family: monospace

  size: 13

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0
